[package]
name = "ratchet_fixture"
version = "0.4.2"
edition = "2021"
description = "Ratchet fixture"
keywords = ["websocket", "async", "futures", "tokio"]
categories = ["network-programming", "asynchronous", "web-programming::websocket"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/swimos/ratchet/"

[dependencies]
ratchet = { package = "ratchet_rs", version = "0.4.2", path = "../ratchet_rs", features = ["split", "deflate", "fixture"] }
tokio = { version = "1.1.1", features = ["io-util"] }
bytes = "1.0"
futures = "0.3.4"

[dev-dependencies]
tokio = { version = "1.1.1", features = ["rt-multi-thread", "macros", "test-util"] }
