[package]
name = "ratchet_deflate"
version = "0.4.2"
authors = ["Swim Inc. developers info@swim.ai"]
edition = "2021"
description = "Permessage Deflate for Ratchet"
keywords = ["websocket", "async", "futures", "tokio", "deflate"]
categories = ["network-programming", "asynchronous", "web-programming::websocket"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/swimos/ratchet/"

[dependencies]
ratchet_ext = { version = "0.4.2", path = "../ratchet_ext" }
thiserror = "1.0"
http = "1.1.0"
bytes = "1.0"
flate2 = { version = "1.0", default-features = false, features = ["zlib"] }
log = "0.4.14"